title: Matt Rubin
markdown: kramdown
kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

asset_pipeline:
  order_css:
    - normalize.css
    # Additional assets will be appended based on their order in the file system.
